football_dbt:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: football-dashboard-490415
      dataset: football_curated
      location: EU
      threads: 4
      timeout_seconds: 300